---
# tasks file for linux.WhiteSur_shell_theme

- name: Checkin for already build theme
  stat:
    path: "~/.themes/{{ shell_theme_folder_name }}"
  register: WhiteSur_shell_theme_present

- name: Desired WhiteSur shell theme
  debug:
    msg: The file {{ shell_theme_folder_name }} exists = {{ WhiteSur_shell_theme_present.stat.exists }}
  when: runned_from_test

- name: Building and installing theme
  block:

  - name: Clonning git repo
    ansible.builtin.git:
      repo: "{{ WhiteSur_shell_theme_repo_url }}"
      dest: /tmp/WhiteSur_theme
      clone: true
      version: "{{ WhiteSur_shell_theme_repo_version }}"
    notify: Removing repo

  - name: Building shell and application theme
    ansible.builtin.command: "/tmp/WhiteSur_theme/install.sh -t {{ WhiteSur_shell_theme_color_variant }} -i {{ WhiteSur_shell_theme_icon_variant }}"
    changed_when: not WhiteSur_shell_theme_present.stat.exists

  when: not WhiteSur_shell_theme_present.stat.exists


- name: Selecting shell theme
  community.general.dconf:
    key: "{{ shell_theme_dconf_key }}"
    value: "{{ shell_theme_dconf_value }}"
    state: present

- name: Seting dark theme cornjob
  cron:
    name: shell-theme-dark
    minute: "0"
    hour: "{{ dark_theme_time }}"
    job: dconf write {{ shell_theme_dconf_key }} "{{ shell_theme_cronjob_dark_value }}"

- name: Seting light theme cornjob
  cron:
    name: shell-theme-light
    minute: "0"
    hour: "{{ light_theme_time }}"
    job: dconf write {{ shell_theme_dconf_key }} "{{ shell_theme_cronjob_light_value }}"

- name: Checking for existance of ~/.bin/
  file:
    path: ~/.local/bin
    state: directory
    mode: '0775'

- name: Creating shell_theme_selector script
  template:
    src: shell_theme_select.sh.j2
    dest: ~/.local/bin/shell_theme_selector.sh
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: u=rwx,g=rwx,o=rx
  notify: Seting on boot cronjob

- name: Theme changing shortcuts
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} THEME SELECTION ALIASES"
    block: |
      alias dark="dconf write /org/gnome/desktop/interface/gtk-theme \"{{ shell_theme_cronjob_dark_value }}\""
      alias light="dconf write /org/gnome/desktop/interface/gtk-theme \"{{ shell_theme_cronjob_light_value }}\""