---
# tasks file for linux.papirus_icon_theme

- name: Checkin for already build theme
  stat:
    path: "~/.icons/{{ icon_theme_folder_name }}"
  register: papirus_icon_theme_present

- name: Desired papirus icon theme
  debug:
    msg: The file {{ icon_theme_folder_name }} exists = {{ papirus_icon_theme_present.stat.exists }}
  when: runned_from_test

- name: Building and installing theme
  block:

  - name: Clonning git repo
    ansible.builtin.git:
      repo: "{{ papirus_icon_theme_repo_url }}"
      dest: /tmp/papirus_icons_repo
      clone: true
      version: "{{ papirus_icon_theme_repo_version }}"
    notify: Removing repo
    
  - name: Building icon theme
    ansible.builtin.command: /tmp/papirus_icons_repo/install.sh -d ~/.icons/ -n papirus-handcrafted {{ papirus_icon_theme_color_variant }}
    changed_when: not papirus_icon_theme_present.stat.exists
    
  when: not papirus_icon_theme_present.stat.exists

- name: Selecting icon theme
  community.general.dconf:
    key: "{{ icon_theme_dconf_key }}"
    value: "{{ icon_theme_dconf_value }}"
    state: present
  

  