---
- name: Checkin for already build theme
  stat:
    path: "~/.icons/{{ icon_theme_folder_name }}"
  register: papirus_icon_theme_present

- name: Desired papirus icon theme is installed
  debug:
    msg: The file {{ icon_theme_folder_name }} exists = {{ papirus_icon_theme_present.stat.exists }}
  when: runned_from_test

- name: Uninstalling papirus theme
  shell:
    cmd: wget -qO- https://git.io/papirus-icon-theme-uninstall | DESTDIR="$HOME/.icons" sh
  become: true
  when: papirus_icon_theme_present.stat.exists

- name: Checkin for already build theme
  stat:
    path: "~/.local/bin/papirus-folders"
  register: papirus_folders_script_present

- name: Desired papirus-folders script is installed
  debug:
    msg: The file papirus-folders script exists = {{ papirus_folders_script_present.stat.exists }}
  when: runned_from_test

- name: Uninstalling papirus-folders script
  shell:
    cmd: wget -qO- https://git.io/papirus-folders-install | env uninstall=true PREFIX=$HOME/.local sh
  when: papirus_folders_script_present.stat.exists
