---
# tasks file for linux.oreo_cursor_theme

- name: Checkin for already build theme
  stat:
    path: "~/.icons/{{ cursor_theme_folder_name }}"
  register: oreo_cursor_theme_present

- name: Desired oreo cursor theme
  debug:
    msg: The file {{ cursor_theme_folder_name }} exists = {{ oreo_cursor_theme_present.stat.exists }}
  when: runned_from_test

- name: Building and installing theme
  block:

  - name: Installing dependencies
    yum:
      name: "{{ oreo_theme_build_dependencies }}"
      state: present
    failed_when: ansible_distribution_file_variety != "RedHat"

  - name: Clonning git repo
    ansible.builtin.git:
      repo: "{{ oreo_cursor_theme_repo_url }}"
      dest: /tmp/oreo_cursor_theme
      clone: true
    notify: Removing repo

  - name: Creating colours.cfg file for build
    template:
      src: colours.conf.j2
      backup: true
      dest: /tmp/oreo_cursor_theme/generator/colours.conf

  - name: Checking for TTY
    shell: tty
    register: currernt_tty
    ignore_errors: true

  - name: Printing current_tty
    debug:
      var: current_tty
    when: runned_from_test

  - name: Generating cursor resources
    shell:
      chdir: /tmp/oreo_cursor_theme
      cmd: "ruby generator/convert.rb > /dev/pts/0"
    changed_when: not oreo_cursor_theme_present.stat.exists
    register: ruby_output

  - name: Displaying ruby output
    debug:
      var: ruby_output
    when: runned_from_test

  - name: Modifying Makefile
    command:
      chdir: /tmp/oreo_cursor_theme
      cmd: "sed -i 's\\$(DESTDIR)$(PREFIX)/share/icons\\~/.icons\\' Makefile"
    changed_when: not oreo_cursor_theme_present.stat.exists

  - name: Building cursor theme
    command:
      chdir: /tmp/oreo_cursor_theme
      cmd: "make build"
    changed_when: not oreo_cursor_theme_present.stat.exists
  
  - name: Installing cursor theme
    command:
      chdir: /tmp/oreo_cursor_theme
      cmd: "make install"
    changed_when: not oreo_cursor_theme_present.stat.exists

  when: not oreo_cursor_theme_present.stat.exists

- name: Selecting cursor theme
  community.general.dconf:
    key: "{{ cursor_theme_dconf_key }}"
    value: "{{ cursor_theme_dconf_value }}"
    state: present

- name: Selecting cursor size
  community.general.dconf:
    key: "{{ cursor_size_dconf_key }}"
    value: "{{ cursor_size_dconf_value }}"
    state: present